# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="robbyrussell"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(command-not-found colorize debian django history-substring-search mercurial pip python)

# User configuration

# Preferred editor for local and remote sessions
export EDITOR="vim"

source $ZSH/oh-my-zsh.sh

# History substring search: bind UP and DOWN arrow keys
zmodload zsh/terminfo
bindkey "$terminfo[kcuu1]" history-substring-search-up
bindkey "$terminfo[kcud1]" history-substring-search-down

# zsh syntax highlighting
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern cursor)

# The following are only executed on login, to prevent duplication and nested shells
if [[ -o login ]]
then
    export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:$PATH"

    # Change to the project directory
    cd /vagrant

    # and activate the virtual environment
    pipenv shell
fi